CREATE TABLE IF NOT EXISTS recommendations (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(255) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `genre` VARCHAR(255) NOT NULL,

  PRIMARY KEY (id)
);
