version: '3.8'
networks:
    production:

services:
    nginx:
        image: nginx:stable-alpine
        ports:
            - '8001:8001'
            - '8011:8011'
            - '8022:8022'
        volumes:
            - './nginx.conf:/etc/nginx/nginx.conf'
        depends_on:
            - user_service
            - movie_service
            - blog_service
        networks:
            - production

    user_service:
        build:
            context: ./user-service
            dockerfile: Dockerfile.prod
        environment:
            - DSN=host=localhost user=postgres password=password dbname=flicksfi port=5432 sslmode=disable TimeZone=Asia/Shanghai
            - SUPER_SECRET_KEY=abc&1*~#^2^#s0^=)^^7%b34
            - IV=123456789012
        mem_limit: 256m
        mem_reservation: 112m
        cpus: 0.35
        cpu_shares: 112
        networks:
            - production

    movie_service:
        build:
            context: ./movie-service
            dockerfile: Dockerfile.prod
        environment:
            - DSN=host=localhost user=postgres password=password dbname=flicksfi port=5432 sslmode=disable TimeZone=Asia/Shanghai
            - SUPER_SECRET_KEY=abc&1*~#^2^#s0^=)^^7%b34
            - IV=123456789012
        mem_limit: 512m
        mem_reservation: 112m
        cpus: 1
        cpu_shares: 256
        networks:
            - production

    blog_service:
        build:
            context: ./blog-service
            dockerfile: Dockerfile.prod
        environment:
            - DSN=host=localhost user=postgres password=password dbname=flicksfi port=5432 sslmode=disable TimeZone=Asia/Shanghai
            - SUPER_SECRET_KEY=abc&1*~#^2^#s0^=)^^7%b34
            - IV=123456789012
        mem_limit: 512m
        mem_reservation: 112m
        cpus: 0.4
        cpu_shares: 112
        networks:
            - production
