package Security

object BannedWord {
    private val bannedWords = Set(
      "<script>",
      "</script>",
      "<iframe>",
      "</iframe>",
      "javascript:",
      "vbscript:",
      "data:text/html",
      "onclick=",
      "onerror=",
      "onmouseover=",
      "onfocus=",
      "eval(",
      "expression(",
      "document.cookie",
      "window.onload",
      "setTimeout(",
      "setInterval(",
      "ActiveXObject(",
      "appendChild(",
      "fromCharCode(",
      "base64,",
      "fromCharCode",
      "location.hash",
      "location.replace",
      "unescape",
      "%3cscript",
      "union select",
      "union all select",
      "information_schema",
      "xp_cmdshell",
      "exec(",
      "INSERT INTO",
      "DELETE FROM",
      "UPDATE ",
      "CREATE TABLE",
      "DROP TABLE",
      "TRUNCATE TABLE",
      "ALTER TABLE",
      "sleep(",
      "benchmark(",
      "../",
      "..\\",
      "file://",
      "%2e%2e%2f",
      "%2e%2e%5c",
      "php://",
      "data://",
      "system(",
      "passthru(",
      "shell_exec(",
      "exec(",
      "popen(",
      "proc_open(",
      "passwd",
      "api_key",
      "secret_key",
      "private_key",
      "oauth_token",
      "credit_card",
      "ssn",
      "social security number",
      "bank_account",
      "<?php",
      "<%",
      "file_get_contents(",
      "curl_exec(",
      "$_GET",
      "$_POST",
      "$_REQUEST",
      "getenv(",
      "require_once(",
      "include_once(",
      "require(",
      "include(",
      "<?xml",
      "<!DOCTYPE",
      "onerror",
      "onload",
      "iframe",
      "onclick=",
      "onerror=",
      "javascript:",
      "vbscript:",
      "%3Cscript%3E",
      "%3Ciframe%3E",
      "data:",
      "expression(",
      "</script>",
      "url(",
      "prompt(",
      "String.fromCharCode",
      "unescape",
      "decodeURIComponent",
      "charCodeAt"
    )

    def is_request_suspicious(request: String): Boolean = {
        bannedWords.exists(request.contains)
    }
}
