@startuml user.database
component Users {
    class v012 {
        -id : int
        +uuid : string
        +username : string
        +email : string
        -ip_address : string
        -country : string
        +createdAt : string
    }

    class v011 {
        -id : int
        +uuid : string
        -secret_word : string
        +username : string
        +username_upper : string
        +email : string
        +email_upper : string
        -ip_address : string
        -country : string
        -regionName : string
        -zip : string
        +createdAt : string
    }

    v011 --> v012 : Remake
}
@enduml
