#!/bin/bash

set -e

# COLORS
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

ENV_FILE=".env"
ENV_PROD_FILE=".env.production"
HOME="$(git rev-parse --show-toplevel)"

# Создание .env файла и добавление переменных
echo -e "${BLUE}Создание файла $ENV_FILE...${NC}"

### USER MICROSERVICE
cd "$HOME/server/user-service"
# Запись переменных окружения в файл
if [ -f "$HOME/server/user-service/$ENV_PROD_FILE" ]; then
    echo -e "${BLUE}Файл $ENV_PROD_FILE уже существует.${NC}"
else
    # Создание .env.production файла и добавление переменных
    echo -e "${BLUE}Создание файла $ENV_PROD_FILE...${NC}"

    cd "$HOME/server/user-service"
    # Запись переменных окружения в файл
    cat <<EOL > $ENV_PROD_FILE
# Переменные окружения
DSN="host=89.213.114.56 user=admin_flicksfi password=quIaus_flicksfi dbname=flicksfi port=5432 sslmode=disable TimeZone=Europe/Samara"
SUPER_SECRET_KEY="abc&1*~#^2^#s0^=)^^7%b34"
IV="123456789012"

LOG_DIR="/root/flicksfi/server/user-service"

GO_ENV=PROD # PROD
EOL
    echo -e "${GREEN}$ENV_PROD_FILE создан!${NC}"
fi

if [ -f "$HOME/server/user-service/$ENV_FILE" ]; then
    echo -e "${BLUE}Файл $ENV_FILE уже существует.${NC}"
else
    # Создание .env.production файла и добавление переменных
    echo -e "${BLUE}Создание файла $ENV_FILE...${NC}"

    cd "$HOME/server/user-service"
    # Запись переменных окружения в файл
    cat <<EOL > $ENV_FILE
# Переменные окружения
DSN="host=localhost user=postgres password=password dbname=flicksfi port=5432 sslmode=disable TimeZone=Europe/Samara"
SUPER_SECRET_KEY="abc&1*~#^2^#s0^=)^^7%b34"
IV="123456789012"

LOG_DIR=""

GO_ENV=DEV # PROD
EOL
    echo -e "${GREEN}$ENV_FILE создан!${NC}"
fi

### MOVIE MICROSERVICE
cd "$HOME/server/movie-service"
# Запись переменных окружения в файл
if [ -f "$HOME/server/movie-service/$ENV_PROD_FILE" ]; then
    echo -e "${BLUE}Файл $ENV_PROD_FILE уже существует.${NC}"
else
    # Создание .env.production файла и добавление переменных
    echo -e "${BLUE}Создание файла $ENV_PROD_FILE...${NC}"

    cd "$HOME/server/movie-service"
    # Запись переменных окружения в файл
    cat <<EOL > $ENV_PROD_FILE
# Переменные окружения
DSN="host=89.213.114.56 user=admin_flicksfi password=quIaus_flicksfi dbname=flicksfi port=5432 sslmode=disable TimeZone=Europe/Samara"
SUPER_SECRET_KEY="abc&1*~#^2^#s0^=)^^7%b34"
IV="123456789012"

LOG_DIR="/root/flicksfi/server/movie-service"

GO_ENV=PROD # PROD
EOL
    echo -e "${GREEN}$ENV_PROD_FILE создан!${NC}"
fi

if [ -f "$HOME/server/movie-service/$ENV_FILE" ]; then
    echo -e "${BLUE}Файл $ENV_FILE уже существует.${NC}"
else
    # Создание .env.production файла и добавление переменных
    echo -e "${BLUE}Создание файла $ENV_FILE...${NC}"

    cd "$HOME/server/movie-service"
    # Запись переменных окружения в файл
    cat <<EOL > $ENV_FILE
# Переменные окружения
DSN="host=localhost user=postgres password=password dbname=flicksfi port=5432 sslmode=disable TimeZone=Europe/Samara"
SUPER_SECRET_KEY="abc&1*~#^2^#s0^=)^^7%b34"
IV="123456789012"

LOG_DIR=""

GO_ENV=DEV # PROD
EOL
    echo -e "${GREEN}$ENV_FILE создан!${NC}"
fi

### BLOG MICROSERVICE
cd "$HOME/server/blog-service"
# Запись переменных окружения в файл
if [ -f "$HOME/server/blog-service/$ENV_PROD_FILE" ]; then
    echo -e "${BLUE}Файл $ENV_PROD_FILE уже существует.${NC}"
else
    # Создание .env.production файла и добавление переменных
    echo -e "${BLUE}Создание файла $ENV_PROD_FILE...${NC}"

    cd "$HOME/server/blog-service"
    # Запись переменных окружения в файл
    cat <<EOL > $ENV_PROD_FILE
# Переменные окружения
DSN="host=89.213.114.56 user=admin_flicksfi password=quIaus_flicksfi dbname=flicksfi port=5432 sslmode=disable TimeZone=Europe/Samara"
SUPER_SECRET_KEY="abc&1*~#^2^#s0^=)^^7%b34"
IV="123456789012"

LOG_DIR="/root/flicksfi/server/blog-service"

GO_ENV=PROD # PROD
EOL
    echo -e "${GREEN}$ENV_PROD_FILE создан!${NC}"
fi

if [ -f "$HOME/server/blog-service/$ENV_FILE" ]; then
    echo -e "${BLUE}Файл $ENV_FILE уже существует.${NC}"
else
    # Создание .env.production файла и добавление переменных
    echo -e "${BLUE}Создание файла $ENV_FILE...${NC}"

    cd "$HOME/server/blog-service"
    # Запись переменных окружения в файл
    cat <<EOL > $ENV_FILE
# Переменные окружения
DSN="host=localhost user=postgres password=password dbname=flicksfi port=5432 sslmode=disable TimeZone=Europe/Samara"
SUPER_SECRET_KEY="abc&1*~#^2^#s0^=)^^7%b34"
IV="123456789012"

LOG_DIR="/root/flicksfi/server/blog-service"

GO_ENV=DEV # PROD
EOL
    echo -e "${GREEN}$ENV_FILE создан!${NC}"
fi
