FROM openjdk:22-slim

RUN apt-get update && apt-get install -y curl && \
    curl -L -o sbt.deb https://github.com/sbt/sbt/releases/download/v1.9.7/sbt-1.9.7.deb && \
    dpkg -i sbt.deb && rm sbt.deb

WORKDIR /app

COPY ./app .

RUN sbt compile

CMD ["java", "-jar", "target/scala-2.13/gateway-service_2.13-0.1.0-SNAPSHOT.jar"]
