FROM ubuntu:22.04

RUN apt update -q && \
    apt install -y -q openjdk-17-jre openjdk-17-jdk-headless && \
    apt install -y -q fontconfig fonts-dejavu curl zip unzip git

RUN curl -s "https://get.sdkman.io" | bash

RUN bash -c "source $HOME/.sdkman/bin/sdkman-init.sh && sdk install sbt"

ENV PATH="$HOME/.sdkman/candidates/sbt/current/bin:$PATH"

WORKDIR /app

COPY ./app .

RUN sbt compile

CMD ["java", "-jar", "target/scala-2.13/gateway-service_2.13-0.1.0-SNAPSHOT.jar"]
