CREATE TABLE IF NOT EXISTS payments (
  id SERIAL PRIMARY KEY,
  uuid VARCHAR(255) NOT NULL,
  email VARCHAR(100) NOT NULL,
  card VARCHAR(50),
  cardEnd VARCHAR(3) NOT NULL,
  total FLOAT NOT NULL,
  paymentAt VARCHAR(255) NOT NULL,
  endingAt VARCHAR(255) NOT NULL,

  UNIQUE (uuid)
);
