#!/bin/sh
set -e

echo "Running pre-commit hook..."

# COLORS
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m'

TOTAL_STEPS=4 # 7
STEP=0
increment_step() {
    STEP=$((STEP + 1))
    echo -e "${BLUE}[STEP $STEP/$TOTAL_STEPS] ${1}${NC}"
}

HOME="$(git rev-parse --show-toplevel)"

# Получаем текущую ветку
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

# Получаем список измененных файлов
CHANGED_FILES=$(git diff --cached --name-only)

### Golang ###
if [ "$CURRENT_BRANCH" = "main" ] && echo "$CHANGED_FILES" | grep -qE '^server/user-service/'; then
    increment_step "Changes in 'user-service' directory detected."

    echo -e "${GREEN}[|] Running formatted and build for user-service...${NC}"
    cd "$HOME/server/user-service"

    # Установка
    go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
    go install golang.org/x/tools/cmd/goimports@latest

    go mod tidy

    make fmt
    make check
    make lint
    make build

    git add .
    echo -e "${GREEN}[+] Success formatted and build for user-service!${NC}"
elif echo "$CHANGED_FILES" | grep -qE '^server/user-service/'; then
    increment_step "Changes in 'user-service' directory detected. Only formatting will be done."
    cd "$HOME/server/user-service"

    make fmt
    make check
    make lint

    git add .
    echo -e "${GREEN}[+] Success formatted for user-service!${NC}"
else
    increment_step "No changes in 'user-service' directory. Skipping actions for user-service."
fi

### Golang ###
if [ "$CURRENT_BRANCH" = "main" ] && echo "$CHANGED_FILES" | grep -qE '^server/movie-service/'; then
    increment_step "Changes in 'movie-service' directory detected."

    echo -e "${GREEN}[|] Running formatted and build for movie-service...${NC}"
    cd "$HOME/server/movie-service"

    # Установка
    go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
    go install golang.org/x/tools/cmd/goimports@latest

    go mod tidy

    make fmt
    make check
    make lint
    make build

    git add .
    echo -e "${GREEN}[+] Success formatted and build for movie-service!${NC}"
elif echo "$CHANGED_FILES" | grep -qE '^server/movie-service/'; then
    increment_step "Changes in 'movie-service' directory detected. Only formatting will be done."
    cd "$HOME/server/movie-service"

    make fmt
    make check
    make lint

    git add .
    echo -e "${GREEN}[+] Success formatted for movie-service!${NC}"
else
    increment_step "No changes in 'movie-service' directory. Skipping actions for movie-service."
fi

### Golang ###
# if [ "$CURRENT_BRANCH" = "main" ] && echo "$CHANGED_FILES" | grep -qE '^server/blog-service/'; then
#     increment_step "Changes in 'blog-service' directory detected."

#     echo -e "${GREEN}[|] Running formatted and build for blog-service...${NC}"
#     cd "$HOME/server/blog-service"
#
#    # Установка
#    go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
#    go install golang.org/x/tools/cmd/goimports@latest
#
#    go mod tidy
#
#    make fmt
#    make check
#    make lint
#    make build
#
#     git add .
#     echo -e "${GREEN}[+] Success formatted and build for blog-service!${NC}"
# elif echo "$CHANGED_FILES" | grep -qE '^server/blog-service/'; then
#    increment_step "Changes in 'blog-service' directory detected. Only formatting will be done."
#    cd "$HOME/server/blog-service"
#
#   make fmt
#   make check
#   make lint
#
#    git add .
#    echo -e "${GREEN}[+] Success formatted for blog-service!${NC}"
# else
#     increment_step "No changes in 'blog-service' directory. Skipping actions for blog-service."
# fi

echo "Husky is successfully!"
